export const SETSERVICE = 'SETSERVICE';
export const SETBARBER = 'SETBARBER';
export const SETSLOT = 'SETSLOT';
export const SETTOTAL = 'SETTOTAL';
export const SETBARBERID = 'SETBARBERID';
export const SETUSERID = 'SETUSERID';
export const SETORGANISATIONID = 'SETORGANISATIONID';
export const SETUSER = 'SETUSER';
export const SETAUTHENTICATION = 'SETAUTHENTICATION';
export const SETUSERCACHE = 'SETUSERCACHE';
export const GETUSERCACHE = 'GETUSERCACHE';
export const SETUPDATE = 'SETUPDATE';

